#!/usr/bin/env python3
"""Generate the catalog from the skill files. This is the "discovery" seed.

Run:  python tools/build_catalog.py

Scans skills/ and writes:
  - catalog/index.json   machine-readable catalog (consumed later by the hub API)
  - catalog/CATALOG.md   human-readable table

Both are generated artifacts — do not edit by hand. CI rebuilds them and fails
if they are out of date, so the catalog never drifts from the source files.
"""

from __future__ import annotations

import json
import os

from skilllib import REPO_ROOT, iter_skills, parse_frontmatter, rel

CATALOG_DIR = os.path.join(REPO_ROOT, "catalog")


def collect() -> list[dict]:
    entries = []
    for dir_name, path in iter_skills():
        try:
            meta, _ = parse_frontmatter(path)
        except ValueError:
            continue
        entries.append(
            {
                "name": meta.get("name", dir_name),
                "description": meta.get("description", ""),
                "version": meta.get("version", ""),
                "owner": meta.get("owner", ""),
                "tags": meta.get("tags", []) or [],
                "path": rel(path),
            }
        )
    entries.sort(key=lambda e: e["name"])
    return entries


def write_index(entries: list[dict]) -> None:
    os.makedirs(CATALOG_DIR, exist_ok=True)
    with open(os.path.join(CATALOG_DIR, "index.json"), "w", encoding="utf-8") as fh:
        json.dump({"skills": entries}, fh, ensure_ascii=False, indent=2)
        fh.write("\n")


def write_markdown(entries: list[dict]) -> None:
    lines = [
        "# Skill Catalog",
        "",
        "_Generated by `tools/build_catalog.py` — do not edit by hand._",
        "",
        "| Skill | Version | Owner | Tags | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for e in entries:
        tags = ", ".join(e["tags"])
        desc = e["description"].replace("|", "\\|")
        lines.append(
            f"| `{e['name']}` | {e['version']} | {e['owner']} | {tags} | {desc} |"
        )
    lines.append("")
    with open(os.path.join(CATALOG_DIR, "CATALOG.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    entries = collect()
    write_index(entries)
    write_markdown(entries)
    print(f"catalog rebuilt: {len(entries)} skill(s) -> catalog/index.json, catalog/CATALOG.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
